### ISSUE TITLE
Problem for images with 1 channel

### ISSUE THREAD

**Issue by noob16** [phillipi/pix2pix#10]
Running the code for 1 input and output channel:
   input_nc = 1,           -- #  of input image channels
   output_nc = 1,          -- #  of output image channels 

lead to this error:
inconsistent tensor size at /usr/local/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7 (dataset.lua:357)

**Comment by junyanz** [comment]
The training code "train.lua" should support images with arbitrary input_nc and output_nc. The error actually comes from data_loader. The current default data_loader only supports input_nc=3, and output_nc=3. 
```lua
   if opt.preprocess == 'regular' 
     local imA, imB = loadImage(path)
     imA, imB = preprocessAandB(imA, imB)
     imAB = torch.cat(imA, imB, 1)
   end
```
For colorization, we write a specific data_loader to support input_nc=1 (L channel), and output_nc=2 (ab channels). 
``` lua
  if opt.preprocess == 'colorization' 
     imAB = loadImageChannel(path)
   end
```
So In `./data/donkey_folder.lua', you need to add a new function.

**Comment by noob16** [comment]
Thanks for your answer. Will there be an update which supports 1 channel images? I tried to add a new function (as you explained) but I think there is more to change and I'm not sure about that...
