### ISSUE TITLE
What should the D-loss and G-loss look like theoretically?

### ISSUE THREAD

**Issue by knaffe** [phillipi/pix2pix#105]
While I train my model, the D-loss and the G-loss will have different tendency with different setting of batch size.
In other words, the D-loss would increase while the G-loss would drop down. Sometimes they are contrary.
So, what should the two loss like in theory? How could I say that I get a good model?

**Comment by junyanz** [comment]
It is quite normal for the G and D losses to go up and down. We mainly check the visual quality of the generated samples.
