### ISSUE TITLE
Strange phenomenon in my extreme experiments

### ISSUE THREAD

**Issue by htoyryla** [phillipi/pix2pix#11]
I am doing what you may consider extreme experiments with your code, as a part of my artistic explorations. See http://liipetti.net/erratic/2016/11/25/imaginary-landscapes-using-pix2pix/ 

In the images at the end of the post you will see a roughly square shape in the middle, having higher frequency content than the rest of the image. It could result from the nature of the experiment (which includes scaling and filling in the missing part), but I came to think of the PatchGAN method described in your paper. Is it used in the code, at all? By default? 

I just happened to think that if the discriminator is looking at an area in the center, then the generator might learn to put more detailed content just there. I don't know yet if this is happening, but it would be a possible explanation for what I am experiencing.

Here's two images as an example, the high frequency "watermark" clearly visible in the center.

![15232095_10154880580548729_3647209952325463915_n](https://cloud.githubusercontent.com/assets/15064373/20624813/c80e25c4-b317-11e6-881e-b49bb648ac82.jpg)

![15178111_10154880580668729_5562908067157761161_n](https://cloud.githubusercontent.com/assets/15064373/20624818/cbd26512-b317-11e6-8685-2c887e3521b5.jpg)

**Comment by phillipi** [comment]
Very cool! I'd be curious to see some input/output pairs for your experiments. Do you mind sharing those?

By default the code uses the 70x70 PatchGAN. You can change this by setting `opt.n_layers_D` to a different value (see usage in models.lua, `defineD_n_layers`).

I'm not sure exactly why you are getting the artifacts in the center. The patch discriminator is run convolutionally across the entire image, so it looks at more than just the center. My guess is the artifact is due to boundary effects: the generator and discriminator both pad the image with zeros, and this means that pixels away from the center of the image have systematically different input than pixels at the center. That definitely creates issues with lots of artifacts near the image borders.

Sometimes these kinds of artifacts will go away if you just train for a really long time :). Another thing you could try is to switch zero padding to mirror padding or something better (will take some coding work).

**Comment by htoyryla** [comment]
I used image pairs like this

![mar05-0144 5](https://cloud.githubusercontent.com/assets/15064373/20639142/1e567240-b3c4-11e6-96e6-f688c24ef44f.jpg)

One can take any landscapes and/or city views, resize them to 512x512px (targets) and then crop the center 256x256 and resize to 512x512 (inputs). So the task may be quite difficult, resizing the input and filling in the missing parts, so now wonder if there are artifacts. 

I tried already training with the same dataset using PixelGAN, too. It looked ok but very blurry and wasn't improving, so I interrupted and then modified my dataset to pairs like this (cropping the target onto a white background, so that the task is only to fill in the missing part).

![mar05-0144 6](https://cloud.githubusercontent.com/assets/15064373/20639162/c35e8f16-b3c4-11e6-80c5-68c666deabcc.jpg)

So far (around 50 epochs of 2500 images) it produces output like this (from the input as above)

![mar05-0144 4](https://cloud.githubusercontent.com/assets/15064373/20639176/11f2fa54-b3c5-11e6-9d1d-5e5f54c2cd7c.jpg)

So this version of the dataset keeps the center quite like the input photo and then fills in the rest, already quite seamlessly. 

For comparison, here's the same image processed using the model trained with the first dataset. The results are more surrealistic but the artifact is visible in the middle. On the other hand, it is interesting to get a quite painting-like quality from only photos. 

![mar05-0144](https://cloud.githubusercontent.com/assets/15064373/20639236/4af9a41e-b3c6-11e6-816b-2142441f78c2.jpg)

My dataset contains many photos from Norway and Switzerland, so the model has a tendency to place mountains on the sides.

I had missed the part that the patches are convolved across the image. I can understand how the zero padding could cause artifacts in the middle when the input is scaled down towards the middle. I will experiment further, changing the code when necessary.

**Comment by ppwwyyxx** [comment]
One thing to note that the generator architecture (the U-net) seems to be specifically designed for image pairs which share a common structure. This is true for all the cases in the paper, but not for your task.

For your task, however, the center region would be roughly shared between input and output, with a different scale. I think that may explain your high-frequency noise in the center: it tries to compress the center patch of the input. I suggest you try a different crop location (e.g. crop a bit on the left but not at the center), and see if the high-frequency region appears at a different place.

**Comment by htoyryla** [comment]
"One thing to note that the generator architecture (the U-net) seems to be specifically designed for image pairs which share a common structure. This is true for all the cases in the paper, but not for your task."

I have been aware of this, and therefore called my experiment "extreme". My second dataset is better suited in this respect. On the other hand, I am after artistically useful effects, and both sets do indeed produce interesting results. So my findings should absolutely not be interpreted as criticism :)

I will experiment with a different crop position, and with different padding time, but this will take time. Looks like I need to install cuda to my second Linux box, too.

**Comment by htoyryla** [comment]
Training with a dataset in which the inputs are cropped out-of-center and resized appear not to produce artifacts (at least not so easily noticeable and not always in the same place). I think this is an interesting finding too. The crop was made towards the upper left corner like this.

![15203379_10154886023803729_2856478817454046303_n](https://cloud.githubusercontent.com/assets/15064373/20646258/bdbec812-b47f-11e6-92b7-1a360a5a566f.jpg)

Here's some samples of the output:

![15232268_10154886018823729_4784194833918312388_n](https://cloud.githubusercontent.com/assets/15064373/20646240/70cb300e-b47f-11e6-85c8-045155f3efe8.jpg)
![15171106_10154886018248729_4003515911918145033_n](https://cloud.githubusercontent.com/assets/15064373/20646242/70ffd890-b47f-11e6-8344-f5b2a3d44baf.jpg)
![15232330_10154886017943729_8406771162816287196_n](https://cloud.githubusercontent.com/assets/15064373/20646241/70fca828-b47f-11e6-8b62-f6ea47b6a886.jpg)
![15181332_10154886016958729_2569737452062136022_n](https://cloud.githubusercontent.com/assets/15064373/20646243/71025890-b47f-11e6-8d80-2d89e96903cb.jpg)
![15193440_10154886016738729_3581271850734963575_n](https://cloud.githubusercontent.com/assets/15064373/20646244/7105b40e-b47f-11e6-879e-22375b9989e5.jpg)

**Comment by htoyryla** [comment]
My second dataset, in which the crop was made in the center, not resized, leaving a white border, is probably a more appropriate task of "filling in what's missing in the picture".  For some images, it works quite well. The center is from the photo, the rest is added by the model.

![dsc00625](https://cloud.githubusercontent.com/assets/15064373/20646267/155afe10-b480-11e6-9529-8dc353ec51d7.jpg)

Sometimes the effect is not so realistic, the image changes towards the edges as if in a dream.

![mar05-0144](https://cloud.githubusercontent.com/assets/15064373/20646429/723928c8-b480-11e6-8d6f-93d258280f63.jpg)

**Comment by htoyryla** [comment]
No need to reopen... this is not really an issue in need of a solution, just discussion. If it is not appropriate here, I will continue in my blog. Anyway, my two recent comments were a response to the suggestions I received, so I felt I should report my findings.

Anyway, great tool even for some more unconventional tasks!
