### ISSUE TITLE
How to evaluate on the cityscape with photo to labels task?

### ISSUE THREAD

**Issue by godisboy** [phillipi/pix2pix#112]
I use the model generate the label images on cityscapes dataset? But I didn't find how to evaluate the result.

**Comment by junyanz** [comment]
We don't have a specific script for that. But you can reuse the evaluation code for label->photo direction. 
given label is the ground truth, and out is the predicted label. 
this line is to compute the overlap between the ground truth and the label. 
https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L49
this line is to compute metrics.
https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L57

**Comment by godisboy** [comment]
Hi junyanz.
I use the script to evaluate with the colour label and itself. All metrics should be equal to 1.00.

**Comment by junyanz** [comment]
how many test images are you evaluating on? Maybe you only a few categories in one test image.

**Comment by godisboy** [comment]
I use 500 val images in the original cityscape database. 
And the result of **gtFine_label(gray level)** val images with itself is in the below:
![image](https://user-images.githubusercontent.com/14243507/32404062-b62be8d4-c183-11e7-88c7-21f684157aaf.png)

**Comment by junyanz** [comment]
It looks good!

**Comment by godisboy** [comment]
Hi junyanz.
I mean I want to test the correctness of the code. 
I evaluate the Ground truth with itself, so all metrics should be equal to 1.00.
But when I evaluate the colour label with itself, it shows the first result.  

Anything wrong with my operation?

![image](https://user-images.githubusercontent.com/14243507/32405200-98bbb686-c19b-11e7-82e3-497ca02400f9.png)

**Comment by junyanz** [comment]
You need to first convert the color map to the label map.

**Comment by godisboy** [comment]
Thanks for your help!
And it's wrong to evaluate with color map directly with that code.

**Comment by liz-hpz** [comment]
@godisboy  Hi,I have [problem](https://github.com/phillipi/pix2pix/issues/161#issue-413651866) in evaluating ground truth itself , could you please give me a hand ?

**Comment by lx7555** [comment]
I want to evaluate cityscapes datasets,because I try to reproduce the fcn score results from pip2pip by using https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix code.
I try many ways.I can not get any results when I run the scripts. All parameters are zero.
I still want to know how to configure the cityspaces dataset
There are three folders with gtFine, originals image, and predictions.
Are the gtFine and predictions color or grayscale? And what is the size of these three types of pictures?
I use python2,caffe.I Is that possible that it was because i was using python2.7 but not python3 ?
@junyanz @godisboy

**Comment by lkiani** [comment]
> I use 500 val images in the original cityscape database.
> And the result of **gtFine_label(gray level)** val images with itself is in the below:
> ![image](https://user-images.githubusercontent.com/14243507/32404062-b62be8d4-c183-11e7-88c7-21f684157aaf.png)

I want to evaluate cityscapes datasets.
I evaluate the Ground truth with itself,
I try many ways.I can not get any results when I run the scripts. All parameters are zero.
can you help me for solve this problem
Thank you

**Comment by ZhangCZhen** [comment]
@godisboy   Hello, I have the same question. How to convert RGB map to label map? Looking forward to your reply! It is important to me, thanks a lot!!

**Comment by junyanz** [comment]
For each RGB pixel, you can find its closest color.

**Comment by A-Little-Nut** [comment]
> > I use 500 val images in the original cityscape database.
> > And the result of **gtFine_label(gray level)** val images with itself is in the below:
> > ![image](https://user-images.githubusercontent.com/14243507/32404062-b62be8d4-c183-11e7-88c7-21f684157aaf.png)
> 
> I want to evaluate cityscapes datasets.
> I evaluate the Ground truth with itself,
> I try many ways.I can not get any results when I run the scripts. All parameters are zero and i get an error(image 2)
> can you help me for solve this problem
> Thank you
> ![image](https://user-images.githubusercontent.com/50620477/57882367-c4658500-7838-11e9-9e31-695852fd153d.png)
> ![image](https://user-images.githubusercontent.com/50620477/57882413-e101bd00-7838-11e9-8ffe-b0ef87f6e346.png)

@lkiani  I have met the same problem. How did you solve the problem?
I really need your help. Thanks a lot
