### ISSUE TITLE
generating pairs issue

### ISSUE THREAD

**Issue by khaulahzia** [phillipi/pix2pix#114]
I have some day images in .jpeg format, i converted them to night images with MATLAB and they are saved in .bmp format. Now the images i have in folder A are in .jpeg and the images in folder B are in .bmp format. The generating pair command runs fine. The folders test, train and val are generated, but there is no pair generated in the folders. The folders are empty.

**Comment by khaulahzia** [comment]
I tried to save my night image in jpeg format, but that disturbs the size of the image and the dimension error shows up while running the generating pair command. How could i generate pair for images in different format?

**Comment by phillipi** [comment]
I think the easier fix will be to simply save all images as jpgs, with the correct dimensions (that should generally be possible).

I'm not sure why the combine_A_and_B script isn't working in your case. I would check what is happening at [this line](https://github.com/phillipi/pix2pix/blob/ab6d3a6b790ee9d279870dccb5c8b66b035b72eb/scripts/combine_A_and_B.py#L46). Are the paths correct? Do im_A and im_B get loaded correctly? Does it fail on imwrite?

**Comment by khaulahzia** [comment]
Fix: convert all bmp images to jpg via online-convert.com.

No issue of path or loading images. Images in A and B should both be in same format necessarily.
