### ISSUE TITLE
Thermal to Color

### ISSUE THREAD

**Issue by xjoshramos** [phillipi/pix2pix#119]
Are there per-trained weights for this translation? Any suggestions on how to train on kaist dataset?

**Comment by janyasir** [comment]
KAIST dataset  will be similar to image segmentation.

I am not sure about existing pre-trained weights for it, but you can train it easily.
Just stitch together input A, and output B images side by side. (The stitching code is also given)
Then give AB stiched image, as training input, by defining network parameters, epoch etc
For testing stitch again testA with testB, and give input stitched testAtestB as input to the network.
