### ISSUE TITLE
Create smooth transitions in the generated images

### ISSUE THREAD

**Issue by kaihuchen** [phillipi/pix2pix#12]
First of all, amazing work!

In the paper it was mentioned that the use of a z noise vector for the generator (as in the standard GAN) was not effective, so in the end the noise is provided by dropouts instead. In the standard GAN I can do things such as sampling the trained generator along  a path in the z space and find smooth transition for those images generated along the path. This has allowed me to create smooth animation of human faces with convincing expressions. Is it fair to say that the randomness in dropouts as used in pix2pix really won't allow me to do the same (i.e., sampling smooth transition in the generated images)?

**Comment by phillipi** [comment]
I'm not sure. I think dropout vs other forms of noise is not so much the issue. But the U-net architecture may pose a problem. There's no low-dimensional bottleneck in the U-net, so I'm not if there's an effective way to sample smooth transitions.

If you switch to a bottlenecked architecture, you might be able to get a nice, disentangled z. I've had limited success with that, but worth exploring more.
