### ISSUE TITLE
WGANGP with pix2pix

### ISSUE THREAD

**Issue by refu0523** [phillipi/pix2pix#121]
I've tried to combine improved WGAN with pix2pix, but I got a very unstable training even got exploded ( NaN). I have also implemented original WGAN with pix2pix, and it works well. It seems like the clipping way does make sure the weight not exploded, but the gradient penalty doesn't work well.
 Does anyone have any idea or experience to combine these two?

**Comment by rohitsaluja22** [comment]
Hi is it possible for you to share the code of original WGAN with pix2pix, and improved WGAN with pix2pix?
