### ISSUE TITLE
day-night data

### ISSUE THREAD

**Issue by cuimiao187561** [phillipi/pix2pix#124]
hello
 I want access to attributes datase ,I sent mail("pylaffont_AT_cs.brown.edu")  to get the data is failed ,can you share the data?my mail: cuimiao188@163.com
thank you very much

**Comment by phillipi** [comment]
You can get the data from http://transattr.cs.brown.edu/

Here are some more instructions: https://github.com/phillipi/pix2pix/issues/8#issuecomment-264963725
