### ISSUE TITLE
On PatchGan

### ISSUE THREAD

**Issue by lucabergamini** [phillipi/pix2pix#125]
Greetings,
As for the output of the patchGan network, after the 1x1 convolutional layer is the resulting map (of size 1x64x64 e.g.) averaged before the loss criterion or just fetched as it is? For What I've understood one of the two holds:
* It's not averaged, resulting in 64x64 different values, representing each a patch score (fake or real)
* It's averaged, resulting in just 1 value, representing the mean score of the image

It should make no differences, as long as it is consistent with the other losses.

**Comment by phillipi** [comment]
The output of netD is an array of patch scores. Then final loss is then the average log loss over this array, and the averaging is computed within [BCECriterion](https://github.com/torch/nn/blob/master/doc/criterion.md#nn.BCECriterion).

**Comment by lucabergamini** [comment]
Perfect, thank you so much and sorry for the silly question :)
