### ISSUE TITLE
What's your configurations for 'inpainting'?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [phillipi/pix2pix#126]
Your default configurations are for 'regular', the results are bad using the default settings.

**Comment by phillipi** [comment]
Can you send more details? I'm not sure what configurations you are referring to.

**Comment by Naruto-Sasuke** [comment]
when 'opt.preprocess == 'inpaint'', then I get very bad results for center-masked inpainting. I wonder what's your opts are, such as 'opt.lambda' or something special from the default setting.

**Comment by phillipi** [comment]
Ah, maybe @tinghuiz can help? He implemented the inpainting.

**Comment by tinghuiz** [comment]
We used the default setting for the inpainting results in the paper. What dataset are you using? Can you show some example results you are getting?

**Comment by Naruto-Sasuke** [comment]
![_809](https://user-images.githubusercontent.com/7830725/35180273-ddf8c816-fda4-11e7-8e40-027bc76fd977.png)
![_808](https://user-images.githubusercontent.com/7830725/35180274-de2c332c-fda4-11e7-81c5-1899a31afc67.png)
![_807](https://user-images.githubusercontent.com/7830725/35180275-de5f84ac-fda4-11e7-8220-5177028b4c19.png)
I use Paris StreetView dataset, and train for 200 epoch with batchsize=32. The default batchsize=1, I wonder whether it matters that much.

**Comment by tinghuiz** [comment]
Can you try testing models from earlier epochs and see if they look better? From our experience, the performance of the inpainting model does deteriorate if it is trained for too long (at least for the StreetView dataset). This is probably more so in your case as your batchSize is 32 times larger...

**Comment by junyanz** [comment]
I will recommend a smaller batchSize (1 or 4)

**Comment by Naruto-Sasuke** [comment]
@tinghuiz I've tried epoch 20, 50, 100, similar terrible results.  I am trying batchSize = 1.

**Comment by tinghuiz** [comment]
Then it's likely the batchSize issue. Let us know how it goes with batchSize=1.

**Comment by Naruto-Sasuke** [comment]
Results of epoch 10, 20, 30, 40, 50, 60 are:
![_810](https://user-images.githubusercontent.com/7830725/35190398-66d9d95a-fe58-11e7-89bd-6a0970095a3b.png)
![_811](https://user-images.githubusercontent.com/7830725/35190399-6c5bed6e-fe58-11e7-9479-6f6bca078779.png)
![_812](https://user-images.githubusercontent.com/7830725/35190401-723b28b2-fe58-11e7-952a-63b8f82e6d30.png)
![_813](https://user-images.githubusercontent.com/7830725/35190402-766d04fa-fe58-11e7-953f-42a5aa3415e5.png)
![_814](https://user-images.githubusercontent.com/7830725/35190403-7a05b04e-fe58-11e7-9fbb-ed0eba8b0d22.png)
![_815](https://user-images.githubusercontent.com/7830725/35190404-7d7ab81e-fe58-11e7-8716-0848f671d0c9.png)

I don't think the results will get better with further training.

**Comment by tinghuiz** [comment]
Cool. These look more reasonable. I think the epoch 30 results look the best (although still slightly worse than our final model).

**Comment by sylviawhoa** [comment]
@Naruto-Sasuke Is there a nice way to run test mode at a specific epoch or did you run after training for 10, 20, etc.? i.e., if you run for 50 epochs can you see what the test looks like at 10? Thanks!

**Comment by junyanz** [comment]
@sylviawhoa  You can. Try using `which_epoch`.

**Comment by sylviawhoa** [comment]
@junyanz nice! thank you!
