### ISSUE TITLE
Extending pix2pix and CycleGan to Hyperspectral images 

### ISSUE THREAD

**Issue by 1eesh** [phillipi/pix2pix#128]
Hi, 

Any advice for someone hoping to extend pix2pix and CycleGan to images with more than three channels in the input/output images ( e.g. : hyperspectral images ) ?

Thanks !

**Comment by junyanz** [comment]
You can write your own data loader and set `input_nc` and `output_nc` to the number of channels in your dataset. For example, here is the [function](https://github.com/phillipi/pix2pix/blob/master/data/donkey_folder.lua#L179) we wrote for colorization (`input_nc=`). Also check out our PyTorch [version](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). It is easier to write customized data loader in python.
