### ISSUE TITLE
cudnn/SpatialConvolution.lua error when training on GPU

### ISSUE THREAD

**Issue by Lienes** [phillipi/pix2pix#129]
I run DATA_ROOT=./datasets/facades name=facades_generation which_direction=BtoA th train.lua. 

And the output : 
transferring to gpu...	
done	
/home/liene/torch/install/bin/luajit: ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:42: attempt to perform arithmetic on field 'groups' (a nil value)

Does it means that i have something wrong with dependencies ?

**Comment by Naruto-Sasuke** [comment]
It will be solved if this patch is merged. You can try it yourself locally. #140

**Comment by EvergreenTree** [comment]
Same problem here, even if this patch is fixed already.

```bash
.../torch_distro/install/bin/luajit: ...o/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:31: attempt $
o perform arithmetic on field 'groups' (a nil value)
stack traceback:
        ...o/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:31: in function 'resetWeightDescriptors'
        ...o/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:105: in function 'func'
        ...b/torch_distro/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        ...b/torch_distro/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        test.lua:117: in main chunk
        [C]: in function 'dofile'
        ...rch_distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
```

Possible reason: in function `cudnn_convert_custom` there is a commented message:
`Warning: cudnn.convert does not work with nngraph yet. Ignoring nn.gModule`
which implies `nn.gModule` is not supported.

Still doing the workaround...
