### ISSUE TITLE
Got error when running  combin_A_and_B.py 

### ISSUE THREAD

**Issue by kaihuchen** [phillipi/pix2pix#13]
Got the following message when trying to use the provided tool combin_A_and_B.py for preparing a new dataset:

Traceback (most recent call last):
  File "combine_A_and_B.py", line 46, in <module>
    im_A = cv2.imread(path_A, cv2.CV_LOAD_IMAGE_COLOR)
AttributeError: 'module' object has no attribute 'CV_LOAD_IMAGE_COLOR'

It turned out that my system has OpenCV3 installed which has some differences from OpenCV2. I changed the offending line to the following and the problem went away:

            im_A = cv2.imread(path_A, cv2.IMREAD_COLOR)

Hope this helps somebody.

**Comment by htoyryla** [comment]
I had the same problem, just replaced both constants with the value 1 (which I looked up somewhere).
