### ISSUE TITLE
Parameters for U-Net decoder

### ISSUE THREAD

**Issue by hsm207** [phillipi/pix2pix#131]
In the appendix of the paper, the U-Net decoder is described as:

![image](https://user-images.githubusercontent.com/2398765/36633274-6179ce8e-1960-11e8-8f9f-adba730ec2b8.png)

I just want to check that the number of filters is correct. I thought the number of filters in the decoder layer should be the same as the number of filters in the encoder layer but in reverse ie 512, 512, 512, 512, 512, 256, 128, 64.

**Comment by junyanz** [comment]
The decoder doubles the number of filters as it takes two kinds of outputs: (1) the previous layer's output and (2) the output from the encoder.
