### ISSUE TITLE
Is it a typo in the models.lua, line 20?

### ISSUE THREAD

**Issue by JiamingJiao** [phillipi/pix2pix#135]
There is a "--" before _nn.SpatialBatchNormalization_, however in the other lines it's "-". Does it influence the results?

**Comment by Naruto-Sasuke** [comment]
https://github.com/phillipi/pix2pix/commit/b479b6b7d37f9d7e87dce7f5e627dc3bb7b4a117

**Comment by junyanz** [comment]
It is not a typo. There should be no batchnorm after that layer.
