### ISSUE TITLE
Set max epochs?

### ISSUE THREAD

**Issue by jkundertgibbs** [phillipi/pix2pix#137]
Hi, I'm testing out your code (thank you!) and cannot find a "max epochs" control to stop the training. Does it stop some other way, like if the error gets below a threshold? 
Thanks for any help with this.

**Comment by jkundertgibbs** [comment]
Solved, I believe. For others interested, it's niter (number of iterations, set to 200 by default) in the train.lua file.

**Comment by phillipi** [comment]
Yep, that's right, it's `niter`.
