### ISSUE TITLE
getBatch: how can I read images sequentially rather than in random order?

### ISSUE THREAD

**Issue by jkundertgibbs** [phillipi/pix2pix#139]
As the subject line states, I'd like to adjust the getBatch function to read in images in a 1,2,3,4.... order, rather than them being randomly selected from the data set. Looking at the data.lua script (I assume this is where getBatch is implemented as it's there), I don't see how images are selected, so I'm having a hard time figuring out how to select them in a non-random order.
Thanks!

**Comment by Naruto-Sasuke** [comment]
opt.serial_batches=1

**Comment by jkundertgibbs** [comment]
Thank you! I'd kind of hard-coded that in, but the opt.... is far preferred. Much appreciated!
