### ISSUE TITLE
Proper aspect ratio to use when preparing own dataset

### ISSUE THREAD

**Issue by kaihuchen** [phillipi/pix2pix#14]
Found the following in train.lua:

   loadSize = 286,         -- scale images to this size
   fineSize = 256,         --  then crop to this size

but the following in test.lua:

    loadSize = 256,           -- scale images to this size
    fineSize = 256,           --  then crop to this size

This looks inconsistent. Was '286' actually a typo and should be '256' instead?

I have found that my own dataset (not 1:1 aspect ratio) always got converted to 1:1 aspect ratio during training and look stretched, instead of being scaled proportionally then cropped which shouldn't look stretched. Should I always prepare my dataset in 1:1 aspect ratio?

**Comment by ppwwyyxx** [comment]
It's not a typo but an augmentation. You can refer to the appendix in the paper for the explanation.

**Comment by phillipi** [comment]
That's right, it's intentional. This adds random jitter at training time, but not at test time. You may get slightly better results with different strategies, like setting loadSize=286 at test time as well (but then the test results will all be slightly cropped).

**Comment by phillipi** [comment]
Oh, and yes, the training code resizes images to 1:1 aspect ratio. At test time, you can pass the flag `... aspect_ratio=2 test.lua` to rescale the results to 1:2 aspect ratio.

**Comment by kaihuchen** [comment]
Ah I see. Thank you all for the quick response!
