### ISSUE TITLE
About random vector z

### ISSUE THREAD

**Issue by o0t1ng0o** [phillipi/pix2pix#144]
Hi, @phillipi 
I meet a problem about your conditional GAN equation.
In the following equation, there's a random vector z. 
LcGAN(G;D) =Ex;y[logD(x; y)]+Ex;z[log(1 - D(x;G(x; z))];

But, when i read codes, i cannot find any random vector which is fed in the generator.
Could you please show me the random vector z in the codes?
^_^

**Comment by junyanz** [comment]
From the [paper](https://arxiv.org/pdf/1611.07004.pdf). 
![image](https://user-images.githubusercontent.com/1924757/41187149-8be87658-6b71-11e8-8319-66ae39703319.png)

We have a follow-up [work](https://junyanz.github.io/BicycleGAN/) to address this issue. You may want to have a look.

**Comment by o0t1ng0o** [comment]
Many thanks~^_^
