### ISSUE TITLE
Where is the random noise vector z?

### ISSUE THREAD

**Issue by BlazeRedlip007** [phillipi/pix2pix#150]
[https://github.com/phillipi/pix2pix/blob/master/train.lua](https://github.com/phillipi/pix2pix/blob/master/train.lua)
If input_nc=3, where is the noise vector?

**Comment by junyanz** [comment]
We didn't use the noise vector in pix2pix. `input_c=3` refers to the number of channels in the input image. Check our this follow-up [work](https://github.com/junyanz/BicycleGAN) if you are interested in using noise vector.
