### ISSUE TITLE
Mirror or flip dataset?

### ISSUE THREAD

**Issue by kex243** [phillipi/pix2pix#157]
Is there any reason (for increasing image quality) to provide flipped or mirrored variants of the original datasets? The code use fragmentation, but seems it doesn do flipping/mirroring. In papers it was mentioned that facades dataset use mirrored images, but, as I understood, it was the set prepared, not the coded inclusion. So, the main question is- if my data (the data the network will work with after the traning) has variety with flipped and mirrored images, or just uses other points of view, is it good to use some flipped pictures from original set to enlarge the data set?
I just use some hand-made conversions to the depth maps from arts and it takes time to create more data for my own dataset.
I just ask it as im not a programmer, and it seems to me that it will do the job- if the traning time is not the key parametr, but quality of the depth map is.

**Comment by junyanz** [comment]
It's for data argumentation, a way to increase the size of the training set. It depends on whether your dataset images are horizontally symmetric or not. Please check this [post](https://medium.com/nanonets/how-to-use-deep-learning-when-you-have-limited-data-part-2-data-augmentation-c26971dc8ced) for more details.

**Comment by kex243** [comment]
Thanks, it helped! In case of characters and gestures or poses both flip and mirroring made recognition of output much more relevant for small dataset increased from 200 pics to 800. Sure, not for absolutely new poses, which are out of dataset, but much better results for looking alike.

**Comment by junyanz** [comment]
Cool. Glad that it helps.
