### ISSUE TITLE
Is there PostprocessHED for python??

### ISSUE THREAD

**Issue by JuHyung-Son** [phillipi/pix2pix#166]
https://github.com/phillipi/pix2pix/blob/master/scripts/edges/PostprocessHED.m

is there python version of this matlab code?

**Comment by Fsbmoraes** [comment]
>https://github.com/phillipi/pix2pix/blob/master/scripts/edges/PostprocessHED.m ...

@jusonn 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by junyanz** [comment]
Not as far as I know. Some operations rely on Pitor's Matlab image [toolbox](https://github.com/pdollar/toolbox).

**Comment by ALISAXXW** [comment]
您的邮件已收到，我会尽快回复~~~
