### ISSUE TITLE
How to deal with color bleed glitches?

### ISSUE THREAD

**Issue by mrgloom** [phillipi/pix2pix#171]
How to deal with color bleed glitches?

I mean artifacts like this:
<img width="859" alt="Screenshot 2019-04-27 at 23 49 06" src="https://user-images.githubusercontent.com/4003908/57183764-5de87a80-6eba-11e9-9959-124ada48197d.png">

It can be just color bleed i.e. color change of it can be hole with color halo.

**Comment by junyanz** [comment]
In this particular case (edges2cats), It is caused by a missing boundary. If you add a boundary in the test image, it will fix it. See our recent repo [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE) for better performance.
