### ISSUE TITLE
Error while executing postprocessHED.n

### ISSUE THREAD

**Issue by israrbacha** [phillipi/pix2pix#183]
Hi, i generate .mat files with batch_hed.py and install pdollar,minGw and successfully compile the edgesNmsMex.cpp, but now the problem is when i run postprocessHED.m it give me error:
find 5085 mat files
Error using predict (line 70)
Not enough input arguments.

Error in PostprocessHED>GetEdge (line 46)
E = 1-predict;

Error in PostprocessHED (line 32)
        E = GetEdge(filePath);

Error in result (line 6)
PostprocessHED(mat_path,out,img,thresh,small)

 Although i specified all the paths accordingly, i have hed_mat_dir and edges_dir is empty right? and the rest of the arguments are default values. i call only postprocessHED function in the script:
mat_path= 'G:\hed\hed_mat_dir\';
edg_dir='G:\hed\edge_dir\';
imgw=256;
thresh=25.0/255.0;
small=5;
PostprocessHED(mat_path,edg_dir,imgw,thresh,small)

**Comment by israrbacha** [comment]
sorry for bothering you, you change the code postprocessingHED.m but it still give me the error:
result
find 5085 mat files
Undefined function or variable 'edge_predict'.

Error in PostprocessHED>GetEdge (line 46)
E = 1-edge_predict;

Error in PostprocessHED (line 32)
        E = GetEdge(filePath);

Error in result (line 6)
PostprocessHED(mat_path,out,img,thresh,small)

i dont understand this "edge_predict" is it a function from piotr's toolbox or argument i need to pass? i call the function on this way:
mat_path= 'G:\hed\hed_mat_dir\';
out='G:\hed\edge_dir\';
img=256;
thresh=25.0/255.0;
small=5;
PostprocessHED(mat_path,out,img,thresh,small)
thanks!

**Comment by junyanz** [comment]
I think you need to rerun the edge detection code. I haven't used MATLAB for a few years. But I guess `predict` is a function recently introduced by MATLAB. Therefore, I changed the variable name to `edge_predict` in both MATLAB and python script. You need to rerun the python script.

**Comment by israrbacha** [comment]
thanks for your reply, i will rerun it but my confusion is what value this "edge_predict"will take if it is a variable?. because GetEdge is called inside postprocessHED function.

**Comment by junyanz** [comment]
`edge_predict` is from `load(filePath)`.

**Comment by israrbacha** [comment]
Hi jun-Yan!
i solve the problem by installing this version of toolbox https://github.com/jmbuena/toolbox.badacost.public actually matlab 2017b or newer  don't support some datatypes in pioter's toolbox. this version make some  changes to the Dtypes like(int->Mwsize).
i use rgb images for .mat generation hope this will be useful. thanks!
