### ISSUE TITLE
 About the size of output image of generator

### ISSUE THREAD

**Issue by schrodingercatss** [phillipi/pix2pix#186]
I want to train pix2pix coloring model with 256 * 256 pictures, and then I can color pictures of any size. How can I make the generator output pictures of any size?

**Comment by junyanz** [comment]
It depends on the generator architecture. The UNet generator used in the original pix2pix only supports images with height and width divisible by 256. You can try other kinds of architecture. For example, the Resnet-based [generator](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L315) supports images with height and width divisible by 4.
