### ISSUE TITLE
couldn't access caffe model fcn score

### ISSUE THREAD

**Issue by aamirk5** [phillipi/pix2pix#192]
Hello there..
pip install caffe isn't working. how to run evaluate.py without caffe. any alternative code?

**Comment by junyanz** [comment]
Unfortunately, Caffe is required for this evaluation.

**Comment by junyanz** [comment]
This [post](https://github.com/phillipi/pix2pix/issues/148#issuecomment-610059908)  is related.

**Comment by aamirk5** [comment]
OK... Thank You so much for your help...
Do you know how to calculate quality evaluation metrics ''VIF, UQI, SSIM''  that matches to the values mentioned in the different papers like PAN, and ID-CGAN... I'm using sewar library but the values i'm getting far different value from their values except ''PSNR''... PSNR is close...
any help will be much appreciated...

https://pypi.org/project/sewar/

I'm using these function from the above mentioned values to get quality evaluation metrics...
from sewar.full_ref import uqi
from sewar.full_ref import psnr
from sewar.full_ref import ssim
from sewar.full_ref import vifp

**Comment by junyanz** [comment]
I haven't done that.
