### ISSUE TITLE
Provide already trained models

### ISSUE THREAD

**Issue by carstenschwede** [phillipi/pix2pix#2]
Amazing project!

It would be great to have some pre-trained models, especially for those without Pascal Titans.

**Comment by junyanz** [comment]
We will add some pre-trained models soon (within 1-2 days).

**Comment by carstenschwede** [comment]
Thanks! Looking forward to it.

**Comment by lekevicius** [comment]
I'd especially appreciate someone building BW-Color model on large diverse image set. On GTX 1080 entire COCO set for 200 epochs would take about 10 days to train.

**Comment by junyanz** [comment]
We just added several pre-trained models. Enjoy!
