### ISSUE TITLE
Black output in colorization tasks (Solved)

### ISSUE THREAD

**Issue by vgsatorras** [phillipi/pix2pix#20]
When working with colorization tasks the output is always a black image. 

I think it is because the code is dividing twice the output image by 255.0 for colorization tasks, once in the function util.deprocessLAB() and again at lines 365 and 366 from train.lua.

```
if image_out==nil then image_out = torch.cat(util.deprocessL(real_A[i2]:float()),util.deprocessLAB(real_A[i2]:float(), fake_B[i2]:float()),3)/255.0
else image_out = torch.cat(image_out, torch.cat(util.deprocessL(real_A[i2]:float()),util.deprocessLAB(real_A[i2]:float(), fake_B[i2]:float()),3)/255.0, 2) end
```

Just removing the 255.0 division in the two attached lines solved the problem.

Thanks for this work, it is amazing!

**Comment by brannondorsey** [comment]
Is this ready to be closed then?

**Comment by junyanz** [comment]
Sure. Will fix it in the future commit.
