### ISSUE TITLE
Some question about Patch Discriminator

### ISSUE THREAD

**Issue by ColaWithIce** [phillipi/pix2pix#25]
Hi,

It is a really good work. Thanks for sharing.

Here is what I didn't well understand. You said the patch discriminator acts like convolution operation to the whole image (256 x 256) in the paper and you achieved this by change the depth of the discriminator. But how do you know the size of receptive field (ie. 16 x 16, 70 x 70)?  Another saying is how can I know the receptive field size when I increase or decrease the depth of the discriminator. Is there a way to calculate the relationship (`od = F(rf)`)between receptive field size (rf x rf) and output size of discriminator (od x od)?

Another one is that the structure of 256 by 256 discriminator seems to be 286 X 286 receptive field not what you wrote 574 X 574 in the paper.

**Comment by tinghuiz** [comment]
The R-CNN repo provides a nice utility for calculating receptive field sizes: https://github.com/rbgirshick/rcnn/blob/master/utils/receptive_field_sizes.m. 

You are right that the 256x256 architecture presented in Appendix 5.1.2 has receptive field of 286x286. There should be another C512 appended in the end (as is the case in the code). Thanks for pointing out the typo. We will update the paper in the future version.

**Comment by mrgloom** [comment]
> You are right that the 256x256 architecture presented in Appendix 5.1.2 has receptive field of 286x286.

Does it make sense to have receptive field bigger than input image size?
