### ISSUE TITLE
using 128px images?

### ISSUE THREAD

**Issue by Jack000** [phillipi/pix2pix#26]
256px images work fine, but when I try loadSize=128 fineSize=128
it errors out with

transferring to gpu...	
done	
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/cudnn/init.lua:58: Error in CuDNN: CUDNN_STATUS_BAD_PARAM (cudnnGetConvolutionNdForwardOutputDim)
stack traceback:
	[C]: in function 'error'
	/home/ubuntu/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:137: in function 'createIODescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:366: in function 'func'
	...e/ubuntu/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...e/ubuntu/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	train.lua:220: in function 'createRealFake'
	train.lua:324: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

is there another parameter I need to change to use smaller images?

**Comment by Jack000** [comment]
ah, it's in models.lua. I'll see myself out...

**Comment by noob16** [comment]
Hi, how did you solve this problem?

**Comment by junyanz** [comment]
Hi noob16, you need to (1) specify loadSize (e.g. 160 or 128) and fineSize (128). (2) remove two layers in the `defineG_unet` function in `models.lua` file. 

We will add more model architectures soon.

**Comment by yeguixin** [comment]
I also encounter the same problem. When I set the loadSize=150 and fineSize=150, the same error occurs. How did you solve it?
