### ISSUE TITLE
Got `internal error in __sub: no metatable` error when I train the sample dataset

### ISSUE THREAD

**Issue by naobit** [phillipi/pix2pix#36]
I followed Getting Started instruction and installed pix2pix.
Then, downloaded facades dataset by `bash ./datasets/download_dataset.sh facades` 
and run `DATA_ROOT=./datasets/facades name=facades_generation which_direction=BtoA th train.lua`

but I got the following error.

```
~/torch-cl/install/bin/luajit: ./models.lua:69: internal error in __sub: no metatable
stack traceback:
	[C]: in function '__sub'
	./models.lua:69: in function 'defineG_unet'
	train.lua:110: in function 'defineG'
	train.lua:146: in main chunk
	[C]: in function 'dofile'
	...i/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010ec81ce0
```

How can I fix this?

- run on Mac OSX
- python2.7

**Comment by limadm** [comment]
I'm investigating this issue and it seems to have its roots in a `torch-cl` file. I registered [an issue there](/hughperkins/distro-cl/issues/20).

**Comment by Quasimondo** [comment]
I am getting the same error. Is there any temporary workaround?

**Comment by phillipi** [comment]
Thanks for the pointer @limadm. Maybe it would work to rewrite defineG_unet without the `__sub` syntactic sugar, instead using the `__call__` operator? You can see examples of how to do this [here](https://github.com/torch/nngraph). Another workaround would be to rewrite defineG_unet using nn rather than nngraph, but that will be a bit cumbersome.

**Comment by Quasimondo** [comment]
So the workaround I found is to reactivate regular torch by reinstalling it. I didn't realize that if you install cl-torch it becomes the default torch. I'm pretty sure there must be a simpler way to switch between the distros, at least this comment suggests it: https://github.com/hughperkins/distro-cl/issues/1 - but this line:
```
source ~/torch/install/bin/torch-activate
luajit -l cunn -e 'nn.testcuda()'
```
gave me some errors (but I might have messed up my torch installation at some earlier point)

**Comment by phillipi** [comment]
Great!

**Comment by limadm** [comment]
You can use cl-torch if you don't use this metamethod, like I did in [this fork](/limadm/pix2pix).

**Comment by hj0921** [comment]
@naobit what method have you used to solve this problem? Thank you!
