### ISSUE TITLE
Running the test.lua example line throws an error

### ISSUE THREAD

**Issue by Quasimondo** [phillipi/pix2pix#37]
It looks to me like there might have been a change in the way test.lua works which has not yet been reflected in the download_model.sh script:

when trying to run the example in the docs (after downloading the pre-trained facades model)
`DATA_ROOT=/home/mario/Documents/pix2pix/datasets/facades/ name=facades which_direction=AtoB phase=val th test.lua`

I get 
`/home/mario/torch-cl/install/bin/luajit: cannot open </home/mario/Documents/pix2pix/checkpoints/facades/latest_net_G.t7> in mode r  at /home/mario/torch-cl/pkg/torch/lib/TH/THDiskFile.c:640`

I could fix this by creating a "checkpoints" folder and then copying /models/facades/facades_label2image.t7 to /checkpoints/facades/latest_net_G.t7 - but of course ideally this should work without a workaround

**Comment by junyanz** [comment]
Yes, you need to rename the model from facades_label2image.t7 to facades/latest_net_G.t7. We will clarify it in README.
