### ISSUE TITLE
Error for training

### ISSUE THREAD

**Issue by noob16** [phillipi/pix2pix#4]
Hi, 

I followed you instructions and tried to train your network with the provided dataset. But I get the following error: 

/usr/local/torch/install/bin/luajit: ./models.lua:52: nn.SpatialConvolution has no negation operator
stack traceback:
	[C]: in function '__unm'
	./models.lua:52: in function 'defineG_unet'
	train.lua:110: in function 'defineG'
	train.lua:147: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Do you know what the problem is?

**Comment by kodeo** [comment]
This looks to be the same as closed issue #3, for which the solution was to install nngraph with:

`luarocks install nngraph`

**Comment by noob16** [comment]
nngrapgh is installed

**Comment by mdm0x0** [comment]
i have the same problem. 
nngraph is installed already, but still this error appears:
torch-cl/install/bin/luajit: ./models.lua:50: nn.SpatialConvolution has no negation operator
stack traceback:
	[C]: in function '__unm'
	./models.lua:50: in function 'defineG_unet'
	train.lua:111: in function 'defineG'
	train.lua:148: in main chunk
	[C]: in function 'dofile'
	...n/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405e90
