### ISSUE TITLE
Sketch2photo datasets available?

### ISSUE THREAD

**Issue by timolins** [phillipi/pix2pix#43]
I would love play around the two sketch2photo datasets from the [paper](https://arxiv.org/pdf/1611.07004v1.pdf). Any chance that you release those as well?

**Comment by junyanz** [comment]
In README, you can find `edges2shoes` and `edges2handbags` in the `Dataset` section.

**Comment by timolins** [comment]
You're right. Those two already exist, but in the paper it says:

> Note that the models were trained on automatically detected edges, but generalize to human drawings.

Seems like it's not exactly the same, but maybe im getting this wrong.

**Comment by junyanz** [comment]
You can find human drawings [here](http://cybertron.cg.tu-berlin.de/eitz/projects/classifysketch/)
