### ISSUE TITLE
luajit out of memory during training

### ISSUE THREAD

**Issue by rdaniel** [phillipi/pix2pix#48]
Hi,

I'm trying to train pix2pix on a particular image labeling task. Things worked fine running the facades demo, although I had to use the CPU on my MacBook since the built-in GPU didn't have enough memory for that task.

I've used the combine_A_and_B.py script to generate new image pairs from about 6k pairs of input and label images. When training, I'm getting an error message:
luajit: not enough memory
 
My command line is below. I've got the display frequency set high so I can see what goes on in early iterations. Would dial that down once more comfortable with what was happening.

Anything I can do about the memory error?

$ DATA_ROOT=./datasets/imageClef/combined name=clef_generation which_direction=AtoB gpu=0 cudnn=0 batchSize=10 save_epoch_freq=5 display_freq=3 th train.lua
{
  cudnn : 0
  name : "clef_generation"
  niter : 200
  batchSize : 10
  n_layers_D : 0
  ndf : 64
  which_model_netG : "unet"
  save_display_freq : 5000
  print_freq : 50
  gpu : 0
  use_GAN : 1
  DATA_ROOT : "./datasets/imageClef/combined"
  serial_batch_iter : 1
  use_L1 : 1
  save_epoch_freq : 5
  output_nc : 3
  checkpoints_dir : "./checkpoints"
  input_nc : 3
  beta1 : 0.5
  continue_train : 0
  which_direction : "AtoB"
  phase : "train"
  fineSize : 256
  condition_GAN : 1
  loadSize : 286
  lambda : 100
  ngf : 64
  preprocess : "regular"
  which_model_netD : "basic"
  display_freq : 3
  display : 1
  display_id : 10
  ntrain : inf
  nThreads : 2
  lr : 0.0002
  flip : 1
  save_latest_freq : 5000
  serial_batches : 0
}
Random Seed: 276	
#threads...2	
Starting donkey with id: 2 seed: 278
table: 0x0f12f520
Starting donkey with id: 1 seed: 277
table: 0x0f14f0a8
./datasets/imageClef/combined
./datasets/imageClef/combined
trainCache	/Users/danielr/Documents/src/pix2pix/cache/_Users_danielr_Documents_src_pix2pix_datasets_imageClef_combined_train_trainCache.t7
Creating train metadata
serial batch:, 	0
table: 0x0f1ed738
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
trainCache	/Users/danielr/Documents/src/pix2pix/cache/_Users_danielr_Documents_src_pix2pix_datasets_imageClef_combined_train_trainCache.t7
Creating train metadata
serial batch:, 	0
table: 0x0f0860f8
running "find" on each class directory, and concatenate all those filenames into a single file containing all image paths for a given class
now combine all the files to a single large file
now combine all the files to a single large file
load the large concatenated list of sample paths to self.imagePath
cmd..gwc -L '/tmp/lua_4R6Gpf' |gcut -f1 -d' '
load the large concatenated list of sample paths to self.imagePath
cmd..gwc -L '/tmp/lua_H4yZFT' |gcut -f1 -d' '
5758 samples found... 0/5758 ...................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 2ms | Step: 2ms          
5758 samples found... 0/5758 ...................] ETA: 0ms | Step: 0ms          
Updating classList and imageClass appropriately
 [=================== 1/1 =====================>] Tot: 2ms | Step: 2ms          
Cleaning up temporary files
Cleaning up temporary files
Dataset Size: 	5758	
define model netG...	
define model netD...	
nn.gModule
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> output]
  (1): nn.SpatialConvolution(6 -> 64, 4x4, 2,2, 1,1)
  (2): nn.LeakyReLU(0.2)
  (3): nn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
  (4): nn.SpatialBatchNormalization (4D) (128)
  (5): nn.LeakyReLU(0.2)
  (6): nn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
  (7): nn.SpatialBatchNormalization (4D) (256)
  (8): nn.LeakyReLU(0.2)
  (9): nn.SpatialConvolution(256 -> 512, 4x4, 1,1, 1,1)
  (10): nn.SpatialBatchNormalization (4D) (512)
  (11): nn.LeakyReLU(0.2)
  (12): nn.SpatialConvolution(512 -> 1, 4x4, 1,1, 1,1)
  (13): nn.Sigmoid
}
running model on CPU	
/Users/danielr/torch/install/bin/luajit: not enough memory

**Comment by phillipi** [comment]
I would check to make sure the gpu is really not being used at all. You can use `nvidia-smi` to check how much gpu memory is being used. I haven't tested CPU mode carefully so there's a chance some memory is still allocated on the gpu.

If that's not the issue, then it's a bit surprising you would run out of memory. Can you profile how much memory your system is using for the process?

General strategies for reducing memory usage would be to reduce the batch size (try setting it to 1), and reduce the image size (will require modifying the net architectures, e.g., by removing the first and last layers of netG and the first layer of netD).

**Comment by rdaniel** [comment]
I turned off the display and the code ran fine. On the CPU it is pretty slow, of course, so I'm going to run it on an AWS GPU instance now.

**Comment by b4zz4** [comment]
I have 1.4GB free as I can limit the memory that use the gpu?

```
...
Epoch: [1][     399 /      400]	 Time: 3.719  DataTime: 0.001    Err_G: 3.4267  Err_D: 0.0299  ErrL1: 0.3935	
End of epoch 1 / 200 	 Time Taken: 938.975	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-4014/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
...
```

**Comment by khaulahzia** [comment]
How to turn off the display?

**Comment by khaulahzia** [comment]
How to turn off the display?

**Comment by phillipi** [comment]
On the command line, you can pass `display=0`

**Comment by khaulahzia** [comment]
i am facing the following error when running training command:
transferring to gpu...
done
THCudaCheck FAIL file=/home/admink/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/admink/torch/install/bin/luajit: /home/admink/torch/install/share/lua/5.1/nn/Module.lua:309: cuda runtime error (2) : out of memory at /home/admink/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
[C]: in function 'Tensor'
/home/admink/torch/install/share/lua/5.1/nn/Module.lua:309: in function 'flatten'
/home/admink/torch/install/share/lua/5.1/nn/Module.lua:326: in function 'getParameters'
train.lua:445: in main chunk
[C]: in function 'dofile'
...mink/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50
How could this issue be resolved?

**Comment by khaulahzia** [comment]
because i still get the same error again and again even if i switched off the display.
i could train fine with just 3 images of size 600*600 and maximum of 10 images of size 128*128.
More than that i fail to train the model with the error i mentioned above. How could i train the model on more images at least 500?

**Comment by phillipi** [comment]
Some ideas are here: https://github.com/phillipi/pix2pix/issues/107

Other quick fixes:
1. Run in CPU mode
2. Run on a cloud service that has more GPU memory, e.g., Amazon EC2
3. Make models smaller (e.g., set `ngf` and `ndf` to be 32 rather than 64)

Really it should be possible to avoid running out of memory as you scale the dataset size. The memory should be constant for any sized dataset as images are only loaded on demand. There may be a leak or some inefficiency that causes more memory to be used for larger datasets. I don't have a quick fix, but I would look at the behavior at the end of an epoch, where temporary variables are cleared and reallocated, since this is where you are getting the memory error.

**Comment by khaulahzia** [comment]
Running in CPU mode will in any way affect the quality of training?

**Comment by phillipi** [comment]
It shouldn't.

**Comment by khaulahzia** [comment]
So what would be the difference of running on GPU or CPU?

**Comment by phillipi** [comment]
The GPU is much faster :) Functionality should be the same, although I haven't thoroughly tested CPU mode myself (seems like others have had it work).

**Comment by khaulahzia** [comment]
So you are suggesting me the slower way for the sake of memory 😏

**Comment by phillipi** [comment]
haha yeah it's an unfortunate tradeoff

**Comment by khaulahzia** [comment]
DATA_ROOT=./datasets/alphabet1 name=blob_placement2 which_direction=AtoB
display=0 ngf=16 ndf=16 gpu=0 cudnn=0 batchsize=10 save_epoch_freq=5 th
train.lua
 worked for me. Thanks.
