### ISSUE TITLE
CPU-only support

### ISSUE THREAD

**Issue by iNDicat0r** [phillipi/pix2pix#5]
Are there any possibilities to get this to work with only CPU?

**Comment by kmader** [comment]
See https://github.com/phillipi/pix2pix/pull/6 or use the master branch of https://github.com/4Quant/pix2pix

**Comment by iNDicat0r** [comment]
Excellent. Thank you Kevin!

**Comment by phillipi** [comment]
Thanks for the fix! Merged.

**Comment by iNDicat0r** [comment]
Update the readme for GPU as optional.
