### ISSUE TITLE
Result in encoder_decoder

### ISSUE THREAD

**Issue by royal-feng** [phillipi/pix2pix#53]
First, thanks for great work!
I tried your code and met some problem,when I choose the opt.which_model_netG = 'encoder_decoder', the output result is a simple color image like it ,such as red color,after some epochs ,it turn blue or other color.
I tried to watch it after the code fake_B = netG:forward(real_A) on the 221 line, but the fake_B still turn simple color image,I want to ask why 'encoder_decoder' could not process the result like 'unet'. If the opt.which_model_netG='unet' ,the result is normal.
![2017-02-25 23 38 48](https://cloud.githubusercontent.com/assets/14287863/23332412/34209ad2-fbb4-11e6-9d1d-8aa6dc28fa90.png)

When I run the demo,the opts I tried is (other opts keep default):
DATA_ROOT=./datasets/facades name=facades_generation which_direction=BtoA which_model_netG = encoder_decoder th train.lua

**Comment by junyanz** [comment]
The encoder-decoder doesn't work when batchSize=1. We will try to fix it soon. For now, please try a batchSize>1.
