### ISSUE TITLE
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by srsani** [phillipi/pix2pix#60]
I am trying to run this code on the data set that was provided by this repo, but I get the following error:

"ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?"

Can you please provide any help or direction towards solving this issue? 

Thanks,
Sohrab

**Comment by ppwwyyxx** [comment]
This is not a tensorflow project.
