### ISSUE TITLE
error when setting output_nc to 1

### ISSUE THREAD

**Issue by brisker** [phillipi/pix2pix#61]
/home/jcc/torch/install/bin/luajit: /home/jcc/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/jcc/research/pix2pix/data/dataset.lua:357: inconsistent tensor size at /home/jcc/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7

**Comment by ustcjerry** [comment]
have the same error when setting inout_nc and output_nc to 1 to train the grayscale to grayscale picture

**Comment by junyanz** [comment]
The training code itself supports output_nc=1, but the data_loader doesn't. You need to write your own custom data_loader to support 1-channel input/output. See this [issue](https://github.com/phillipi/pix2pix/issues/10) for more details.
