### ISSUE TITLE
Needs transformation of human face edge to handbag

### ISSUE THREAD

**Issue by voronoipotato** [phillipi/pix2pix#7]
This will highlight how the model accounts for images that does not fit the expected input. 

Thanks.

**Comment by phillipi** [comment]
Can you explain the request in more detail?

**Comment by ppwwyyxx** [comment]
I think what he meant is, it'll be very interesting to see what the output of a (handbag edge -> handbag) model is, given human face edge as input.

**Comment by phillipi** [comment]
Ah yeah that would be cool to try. Will try when I get a chance.

**Comment by ppwwyyxx** [comment]
I trained the model in tensorpack today and tried this myself, with the provided facades dataset:
![out](https://cloud.githubusercontent.com/assets/1381301/20590149/6c720af6-b1ef-11e6-81b4-5d7589f4c944.jpg)
left: input. right: output

It's trying very hard to fill the texture following the given structure.. will do some more experiments once there are more datasets available.

**Comment by phillipi** [comment]
Looks interesting. Can you give some more details on what you did? Is this the model trained on regular facades applied to zoomed in facades?

**Comment by ppwwyyxx** [comment]
Exactly. It's running on some randomly zoomed-in 50x50 facades. The training code is [here](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/GAN/Image2Image.py).
I also used the output building images as input instead (that was a AtoB/BtoA mistake actually), and got something like this:
![1124-03 18 34](https://cloud.githubusercontent.com/assets/1381301/20591138/042756b2-b1f5-11e6-87d4-a3150b30c98e.png)

**Comment by voronoipotato** [comment]
yeah pp it seems like it's at risk of pareidolia when it's zoomable, you might see a building in a window etc.  Even humans have this problem when ... uh .. chemically overstimulated. The duck bag is what gave me the idea of turning a human face edge into a bag image.

**Comment by ppwwyyxx** [comment]
Thanks for the newly released dataset. I trained a shoes model, and run it on handbag edges. The results are interesting. 
![a](https://cloud.githubusercontent.com/assets/1381301/20954009/8305dc82-bc05-11e6-9d62-4612745f0cca.png)
Trained with more data of different types it might do a more general sketch2photo.

**Comment by junyanz** [comment]
Really cool!! FYI, we just added some scripts for extracting the edge maps from photos. Look forward to seeing sketch2photo model for other categories/data.

**Comment by rjpeart** [comment]
Realise this is a closed issue, but wondered if this may be of interest.
Have been exploring how much difference the level of detail in edges makes to the final output.
Using the pre-trained edges>shoes model.

Struggles with lots of detail as you can see, but also with too little. There's a sweet-spot in between. Not a useful experiment, but a fun one at least.


<img width="1173" alt="screen shot 2017-02-04 at 11 10 46 pm" src="https://cloud.githubusercontent.com/assets/2930635/22619675/dce1bf06-eb34-11e6-8e29-ea50905ac0de.png">
<img width="1372" alt="screen shot 2017-02-04 at 11 09 51 pm" src="https://cloud.githubusercontent.com/assets/2930635/22619674/dce137ca-eb34-11e6-959e-2d06d9dfe756.png">
<img width="1363" alt="screen shot 2017-02-04 at 11 09 04 pm" src="https://cloud.githubusercontent.com/assets/2930635/22619676/dce204de-eb34-11e6-99ed-6f45c535031e.png">

**Comment by voronoipotato** [comment]
Thanks rjpeart! I appreciate you putting time in!
