### ISSUE TITLE
1-predict line 84  in   POSTprocessHED.m

### ISSUE THREAD

**Issue by IcedDoggie** [phillipi/pix2pix#70]
Hi there,

May I know what are the inputs for predict function of the specific line? Or which model are you using for the predict function? 

Thanks and look forward to your reply soon.

**Comment by junyanz** [comment]
The python script saves the variable "predict" to the mat file: https://github.com/phillipi/pix2pix/blob/master/scripts/edges/batch_hed.py#L79

**Comment by IcedDoggie** [comment]
Thanks junyanz! This is my working code:

```
function [E] = GetEdge(filePath)

predict = load(filePath);
% disp(predict);
predict = predict(1).predict;

E = 1-predict;

end
```

Have a nice day!
