### ISSUE TITLE
Image stretches out after PostprocessHED.m

### ISSUE THREAD

**Issue by IcedDoggie** [phillipi/pix2pix#72]
Good day.

The image seems to stretch out after the function above. The example is as below:
![1](https://cloud.githubusercontent.com/assets/4167312/24750717/7139d118-1af9-11e7-8247-d45a253cc426.jpg)
![1](https://cloud.githubusercontent.com/assets/4167312/24750823/dd43168a-1af9-11e7-8bbf-3f21298ac0ad.jpg)

**Comment by IcedDoggie** [comment]
Apparently it's my own mistake, I didn't resize my image. Sorry for that.

**Comment by gxlcliqi** [comment]
Can you please kindly point out where to resize the image? I meet the same problem with you.

**Comment by IcedDoggie** [comment]
Terribly sorry, I have forgotten on this part. But I remember there's a default size for the function, you need to resize it according to the default size.

**Comment by gxlcliqi** [comment]
Thanks for you reply! After searching I realize the problem I meet is as an [issue](https://github.com/s9xie/hed/issues/33) relate to the HED project and I can't find the solution yet
