### ISSUE TITLE
How to get intermediate output in U-net?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [phillipi/pix2pix#73]
For example, I want to get the output of d1_ ,how can I do?
```
local out = netG:forward(input)
-- how to get the ouput of d1_  then?
```

**Comment by Quasimondo** [comment]
I explained a workaround for this in this closed issue: https://github.com/phillipi/pix2pix/issues/65

**Comment by Naruto-Sasuke** [comment]
Excellent! We've got the idea. Thank you!
