### ISSUE TITLE
Adding the L1 loss for optimizer

### ISSUE THREAD

**Issue by dmarnerides** [phillipi/pix2pix#78]
For the optimization of the generator, the L1 gradients are added when calling `generator:backward()`, but fGx returns only `errG`. 
Shouldnt it return `errG + opt.lambda * errL1` ?

**Comment by dmarnerides** [comment]
Sorry, didn't really think it through. The actual loss doesn't matter, since we only use the gradient for updating the parameters.

**Comment by phillipi** [comment]
That's a good point, it really should return `errG + opt.lambda * errL1`! I think you're right that it doesn't actually matter though since the return value isn't used...
