### ISSUE TITLE
more datasets available？

### ISSUE THREAD

**Issue by SJTUzhanglj** [phillipi/pix2pix#8]
Hello, the codes and tutorials you provided work well. And i also wanna try some other datasets shown in your paper, can you provided these datasets?

**Comment by junyanz** [comment]
We are working on uploading more datasets.

**Comment by brannondorsey** [comment]
Great to hear, really loving playing with the facades dataset for now :) Any ETA on when the day->night or edges->photo datasets might be up? Don't mean to bug, just really excited to get my hands on some more data to play with. Awesome work!

**Comment by junyanz** [comment]
We just added 4 more datasets. Enjoy!

**Comment by junyanz** [comment]
Just fixed. Thanks for pointing it out.

**Comment by Liberus** [comment]
Thanks for you work! Still waiting for day/night dataset. Also would be nice to hear if you made some preprocessing of dataset - like on what attributes you decided to join images in day/night dataset, should pairs be unique and etc. This might really help for people like me, since I'm trying on different datasets and/or different transitions. Thanks in advance!

**Comment by junyanz** [comment]
Hi Liberus, we use Sun attribute datasets (https://cs.brown.edu/~gen/sunattributes.html). We cannot share with you as we don't have the copyright. Instead, you should be able to download images from their website. We use attribute like "night" or "daylight".

**Comment by Liberus** [comment]
oh, thanks.

Can you also answer my other question about dataset preparation? I can see that this dataset includes 14340 images, how did you achieve 17k images(I'm pretty sure I saw this number somewhere about training day/night )? Did you just merged all day photos to all night photos?(a.k.a. many to many) Or used some filtering before it?

**Comment by junyanz** [comment]
There are ~ 100 webcams from the dataset. For each webcam, we created all day photos ("night" attribute < 0.1) to all night photos. ("night" attribute > 0.8). I think there might be better ways to create the dataset . Unfortunately, you only have ~100 different natural scenes no matter what you do. Let us know if you find a larger dataset.

**Comment by Liberus** [comment]
Thanks! There is one really big dataset(250r images) but it will be public next year(maybe in February) so until then transsattr should do! Thanks

**Comment by cuimiao187561** [comment]
I want access to attributes datase ,I sent mail("pylaffont_AT_cs.brown.edu") to you get data is failed.Can you tell me download dataset(http://transattr.cs.brown.edu/)email?

**Comment by ArkaJU** [comment]
Did you get the day-night dataset?

**Comment by junyanz** [comment]
See [here](https://github.com/phillipi/pix2pix#datasets).

**Comment by ArkaJU** [comment]
The email they have given seems to be invalid, how to get access?

**Comment by junyanz** [comment]
You can download the dataset following the [instruction](https://github.com/phillipi/pix2pix#datasets)
