### ISSUE TITLE
The question about Unet

### ISSUE THREAD

**Issue by vinthony** [phillipi/pix2pix#81]
Hi everyone,

Could anyone explain why  `leakyReLU`  were used in the "Conv" parts of UNet and `ReLU` were used in the "DeConv" parts of UNet? what is the purpose of this different design?

thanks.

**Comment by phillipi** [comment]
It's based on the [DCGAN](https://arxiv.org/abs/1511.06434) design choices. They found it to help, but I'm not exactly sure why, and we didn't test it ourselves.
