### ISSUE TITLE
Facebook in license

### ISSUE THREAD

**Issue by javl** [phillipi/pix2pix#89]
Maybe I'm missing something and pix2pix was made for Facebook, but this part in the license seems a bit off? (small copy-paste error?)

    Neither the name Facebook nor the names of its contributors may be
    used to endorse or promote products derived from this software without 
    specific prior written permission.

**Comment by brannondorsey** [comment]
That appears to be in the BSD License from DCGAN Torch.

**Comment by javl** [comment]
You're right, so actually not an issue with pix2pix repo, sorry. Closing.
