### ISSUE TITLE
How to use 512x512 as input and output layer sizes?

### ISSUE THREAD

**Issue by orenyomtov** [phillipi/pix2pix#91]
I would like to use 512x512 as the input and output layer sizes.

**Comment by Quasimondo** [comment]
Just set the fineSize=512 argument and hope that your GPU memory is sufficient.

**Comment by orenyomtov** [comment]
Oh sweet, is there no need to add layers or do anything else?

**Comment by Quasimondo** [comment]
It works like that, but I guess you could add another layer if you wanted to. In that case you'd have to add the arguments: 
which_model_netD=n_layers n_layers_D=4 
(since the default 'basic' model uses 3 layers).
