### ISSUE TITLE
Surface appearance. 

### ISSUE THREAD

**Issue by 32nguyen** [phillipi/pix2pix#93]
Hi,
Very impressive work. I would like to ask a question which is:
 - In this work, the output image and input image will not have the same surface appearance (like pixel intensity), they just have the same underlying structure, even if my training data has relevant intensity for input and output, is this right?

Bests,

**Comment by phillipi** [comment]
It depends on the training data. The model will try to make outputs that look like the training outputs. If the training outputs share structure with the training inputs, e.g., have the same intensities, then the model will likely learn this.
