### ISSUE TITLE
Service unavailable when trying to get facades

### ISSUE THREAD

**Issue by ashleyjamesbrown** [phillipi/pix2pix#94]
`bash ./datasets/download_dataset.sh facades
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2017-06-23 18:48:53--  https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/facades.tar.gz
Resolving people.eecs.berkeley.edu... 128.32.189.73
Connecting to people.eecs.berkeley.edu|128.32.189.73|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-06-23 18:48:55 ERROR 503: Service Unavailable.`

**Comment by junyanz** [comment]
It works for me. Would you be able to download the dataset via the [link](https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/facades.tar.gz)?

**Comment by ashleyjamesbrown** [comment]
Yup that works. :-) Thanks.
