### ISSUE TITLE
PostprocessHED.m  runtime error

### ISSUE THREAD

**Issue by johntessar** [phillipi/pix2pix#95]
function [E] = GetEdge(filePath)
load(filePath);
E = 1-predict;
end

turned out error "predict (line 69) too few parameters", how should i modify it?

**Comment by junyanz** [comment]
@johntessar Have you generated the edge map files using the Python script? Could you double check if the file [filePath] exists?

**Comment by johntessar** [comment]
@junyanz 
when debugging, the load() runs fine, it's the predict function prompts error, and i do put the .mat file that batch_hed.py generated into filePath :)

**Comment by thinkrc** [comment]
@johntessar 
predict in PostprocessHED.m should be a matrix, has a same name with function predict.m in some version of Matlab.

**Comment by YutingCCC** [comment]
I met the same problem. Have you solved it?

**Comment by phillipi** [comment]
This can happen if `load(filePath)` does not actually load the variable `predict`. I would double check that the variable `predict` exists, as a matrix, after the line `load(filePath)`. The following change might help (or at least make the error message more informative):

`data = load(filePath);
E = 1-data.predict;`
