### ISSUE TITLE
Missing something in pixelGAN code?

### ISSUE THREAD

**Issue by aneesh3108** [phillipi/pix2pix#98]
Hello, 

I am looking at the models.lua file - the code for pixelGANs is: 

> function defineD_pixelGAN(input_nc, output_nc, ndf)
>     local netD = nn.Sequential()
>     
>     -- input is (nc) x 256 x 256
>     netD:add(nn.SpatialConvolution(input_nc+output_nc, ndf, 1, 1, 1, 1, 0, 0))
>     netD:add(nn.LeakyReLU(0.2, true))
>     -- state size: (ndf) x 256 x 256
>     netD:add(nn.SpatialConvolution(ndf, ndf * 2, 1, 1, 1, 1, 0, 0))
>     netD:add(nn.SpatialBatchNormalization(ndf * 2)):add(nn.LeakyReLU(0.2, true))
>     -- state size: (ndf*2) x 256 x 256
>     netD:add(nn.SpatialConvolution(ndf * 2, 1, 1, 1, 1, 1, 0, 0))
>     -- state size: 1 x 256 x 256
>     netD:add(nn.Sigmoid())
>     -- state size: 1 x 30 x 30
>         
>     return netD

Can someone explain how state size:1 x 256 x 256 became 1 x 30 x 30 just post adding the nn.Sigmoid() layer?
Thanks!

**Comment by junyanz** [comment]
There was a typo in the comment. I just fixed it.

**Comment by aneesh3108** [comment]
Thank you @junyanz
